# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: commit
        run: |
            git config user.email "battlographer@github.com"
            git config user.name "Github"
            git add -A && git commit -m "Updated code"

      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        continue-on-error: true
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "inheritproject" #Must be unique in Heroku
          heroku_email: "inheritproject2021@gmail.com"
          branch: "main"
          buildpack: heroku/nodejs
          appdir: express
