# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
#       - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
#         with:
#           api_key: ${{secrets.HEROKU_API_KEY}}
#           email: "inheritproject2021@gmail.com"
#           app_name: "inheritproject"
#           branch: "master"
#           subfolder: "Express"
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: "inheritproject2021@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "inheritproject"
          useforce: true,
          procfile: "worker: npm start",
          buildpacks: "['https://github.com/heroku/heroku-buildpack-nodejs.git','https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git']"       
